requires 'Ark';
requires 'DateTime';
requires 'DBIx::Class';
requires 'FindBin::libs';
requires 'GitDDL';
requires 'SQL::Translator';
requires 'Path::Class';
requires 'String::CamelCase';
requires 'Text::MicroTemplate::Extended';
requires 'Text::MicroTemplate::DataSection';

